-- Table: save_situacao_juridica_incluir_processo
CREATE TABLE IF NOT EXISTS "save_situacao_juridica_incluir_processo" (
    "ID" SERIAL PRIMARY KEY,
    "ID_Caso" INTEGER,
    "SJIP_Numero" TEXT,
    "SJIP_Classe_Tipo" TEXT
);

-- Table: save_situacao_juridica2
CREATE TABLE IF NOT EXISTS "save_situacao_juridica2" (
    "ID_Caso" INTEGER PRIMARY KEY,
    "SJ2_Resultado_Julgamento" TEXT,
    "SJ2_Tempo_Pena" TEXT,
    "SJ2_Inicio_Cumprimento" TIMESTAMP,
    "SJ2_Regime" TEXT,
    "SJ2_Apuracao_Investigacao" TEXT,
    "SJ2_Apuracao_Invest_Especif" TEXT,
    "SJ2_Pedido_Reparacao_Denuncia" TEXT,
    "SJ2_Tipo_Danos" TEXT,
    "SJ2_Tipo_Danos_Especif" TEXT,
    "SJ2_Condenacao_Reparacao" TEXT,
    "SJ2_Condenacao_Repar_Especif" TEXT,
    "SJ2_Demanda_Info_Participacao_Especif" TEXT,
    "SJ2_Demanda_Info_Participacao_Especif2" TEXT,
    "SJ2_Demanda_Memoria_Verdade_Especif" TEXT,
    "SJ2_Demanda_Memoria_Verdade_Especif2" TEXT,
    "SJ2_Demanda_Justica_Diligencia_Especif" TEXT,
    "SJ2_Demanda_Justica_Diligencia_Especif2" TEXT,
    "SJ2_Demanda_Apoio_Assistencia_Especif" TEXT,
    "SJ2_Demanda_Apoio_Assistencia_Especif2" TEXT,
    "SJ2_Demanda_Seguranca_Especif" TEXT,
    "SJ2_Demanda_Seguranca_Especif2" TEXT,
    "SJ2_Demanda_Protecao_Nao_Revitimizacao_Especif" TEXT,
    "SJ2_Demanda_Protecao_Nao_Revitimizacao_Especif2" TEXT,
    "SJ2_Demanda_Protecao_Psicologica" BOOLEAN,
    "SJ2_Demanda_Protecao_Psicologica_Especif" TEXT,
    "SJ2_Demanda_Protecao_Psicologica_Especif2" TEXT,
    "SJ2_Demanda_Protecao_Documental_Especif" TEXT,
    "SJ2_Demanda_Protecao_Documental_Especif2" TEXT,
    "SJ2_Demanda_Compensacao_Reparacao_Especif" TEXT,
    "SJ2_Demanda_Compensacao_Reparacao_Especif2" TEXT,
    "SJ2_Demanda_Tratamento_Digno_Especif" TEXT,
    "SJ2_Demanda_Info_Participacao" BOOLEAN,
    "SJ2_Demanda_Memoria_Verdade" BOOLEAN,
    "SJ2_Demanda_Justica_Diligencia" BOOLEAN,
    "SJ2_Demanda_Apoio_Assistencia" BOOLEAN,
    "SJ2_Demanda_Seguranca" BOOLEAN,
    "SJ2_Demanda_Protecao_Nao_Revitimizacao" BOOLEAN,
    "SJ2_Demanda_Protecao_Documental" BOOLEAN,
    "SJ2_Demanda_Compensacao_Reparacao" BOOLEAN,
    "SJ2_Demanda_Tratamento_Digno" BOOLEAN,
    "SJ2_Demanda_Compensacao_Reparacao_Especif_OutraForma" TEXT,
    "SJ2_Demanda_Tratamento_Digno_OutraForma" TEXT,
    "SJ2_Prot_Nao_Revit_Med_Caut_Especif" TEXT,
    "SJ2_Prot_Nao_Revit_Med_Caut_Especif2" TEXT
);
